{% set name = "pyearth" %}
{% set git_rev = "master" %}
{% set version = "0.1.26" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_rev: {{ git_rev }}
  git_url: https://github.com/changliao1025/pyearth

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - numpy
    - gdal    
    - matplotlib-base
    - cartopy

test:
  imports:
    - pyearth
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/changliao1025/pyearth
  summary: Python for Earth Science.
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - changliao1025
